services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USERNAME}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - SERVER_COUNTRIES=United States
    ports:
      - 8080:8080     # qBittorrent Web UI
      - 6881:6881     # qBittorrent TCP
      - 6881:6881/udp # qBittorrent UDP
      - 9117:9117     # Jackett
      - 7878:7878     # Radarr
      - 8989:8989     # Sonarr
    restart: unless-stopped
    networks:
      - gluetun_net

  plex:
    image: plexinc/pms-docker
    container_name: plex
    hostname: plex
    environment:
      - TZ=America/New_York
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      # - 1900:1900/udp
      - 32410-32414:32410-32414/udp
    volumes:
      - /home/brescou/Plex/database:/config
      - /home/brescou/Plex/transcode_tmp:/transcode
      - /media/brescou/Plex/data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - gluetun_net

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - WEBUI_PORT=8080
    volumes:
      - /home/brescou/qbittorrent/config:/config
      - /media/brescou/Plex/data/torrents:/downloads
    restart: unless-stopped
    network_mode: service:gluetun

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /home/brescou/jackett/config:/config
      - /home/brescou/jackett/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /home/brescou/sonarr/config:/config
      - /media/brescou/Plex/data/series:/tv
      - /media/brescou/Plex/data/torrents:/downloads
    restart: unless-stopped
    network_mode: service:gluetun

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /home/brescou/radarr/config:/config
      - /media/brescou/Plex/data/movies:/movies
      - /media/brescou/Plex/data/torrents:/downloads
    restart: unless-stopped
    network_mode: service:gluetun


networks:
  gluetun_net:
    driver: bridge
