services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USERNAME}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - SERVER_COUNTRIES=United States
    volumes:
      - /home/brescou/gluetun/config:/gluetun
    ports:
      - 8080:8080    # qBittorrent
      - 9117:9117    # Jackett
      - 7878:7878    # Radarr
      - 8989:8989    # Sonarr
      # - 8191:8191    # FlareSolverr
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - gluetun_net

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    hostname: plex
    environment:
      - TZ=America/New_York
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      # - 1900:1900/udp
      - 32410-32414:32410-32414/udp
    volumes:
      - /home/brescou/Plex/database:/config
      - /home/brescou/Plex/transcode_tmp:/transcode
      - /media/brescou/Plex/data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia   
    restart: no
    networks:
      - gluetun_net

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - WEBUI_PORT=8080
    volumes:
      - /home/brescou/qbittorrent/config:/config
      - /media/brescou/Plex/data/torrents:/downloads
    restart: no
    network_mode: service:gluetun

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /home/brescou/jackett/config:/config
      - /home/brescou/jackett/downloads:/downloads
    restart: no
    network_mode: service:gluetun
    # networks:
    #   custom_network:
    #     ipv4_address: 192.168.100.2

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /home/brescou/sonarr/config:/config
      - /media/brescou/Plex/data/tv:/tv
      - /media/brescou/Plex/data/torrents:/downloads
    restart: no
    network_mode: service:gluetun

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /home/brescou/radarr/config:/config
      - /media/brescou/Plex/data/movies:/movies
      - /media/brescou/Plex/data/torrents:/downloads
    restart: no
    network_mode: service:gluetun

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    # network_mode: service:gluetun
    ports:
      - 8191:8191
    # networks:
    #   custom_network:
    #     ipv4_address: 192.168.100.2


networks:
  gluetun_net:
    driver: bridge
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24