version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USERNAME}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - SERVER_COUNTRIES=United States
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    hostname: plex
    environment:
      - TZ=America/New_York
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1901:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /home/brescou/Plex/database:/config
      - /home/brescou/Plex/transcode_tmp:/transcode
      - /media/brescou/Plex1:/data
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - WEBUI_PORT=8080
    volumes:
      - /home/brescou/Plex/:/config
      - /media/brescou/Plex1:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
