version: "3"
services:
  nordvpn:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USERNAME}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - SERVER_COUNTRIES=United States
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    hostname: plex
    environment:
      - TZ=America/New_York
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1901:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /home/brescou/Plex/database:/config
      - /home/brescou/Plex/transcode_tmp:/transcode
      - /media/brescou/Plex:/data
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /home/brescou/qbittorrent/config:/config
      - /media/brescou/Plex:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    network_mode: service:nordvpn
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/brescou/sonarr/config:/config
      - /media/brescou/Plex:/tv
      - /media/brescou/Plex:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    network_mode: service:nordvpn
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/brescou/radarr/config:/config
      - /media/brescou/Plex:/movies
      - /media/brescou/Plex:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    network_mode: service:nordvpn