networks:
  vpn:
    driver: bridge

services:
  plex:
    profiles: ["plex", "all"]
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: no
    runtime: nvidia
    environment:
      - TZ=Europe/Paris
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://192.168.2.41:32400/
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - /home/brescou/Plex/database:/config
      - /home/brescou/Plex/transcode_tmp:/transcode
      - /media/brescou/Plex/data:/data
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb


  nordvpn:
    profiles: ["torrent", "all"]
    container_name: nordvpn
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USERNAME}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - SERVER_COUNTRIES=Canada
      - SERVER_CITIES=Toronto
    ports:
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr  
      - 9117:9117 # Jackett
      - 8191:8191 # Flaresolverr
      - 8112:8112 # Deluge
      - 6881:6881 # Deluge
      - 6881:6881/udp # Deluge
      - 9696:9696 # Prowlarr
    restart: unless-stopped
    networks:
      - vpn

  flaresolverr:
    profiles: ["torrent", "all"]
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - DRIVER=nodriver
    restart: no
    depends_on:
      - nordvpn
    network_mode: service:nordvpn

  deluge:
    profiles: ["torrent", "all"]
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - DELUGE_LOGLEVEL=info
    volumes:
      - /home/brescou/deluge/config:/config
      - /media/brescou/Plex/data/torrents:/downloads
    restart: no
    depends_on:
      - nordvpn
    network_mode: service:nordvpn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8112"]
      interval: 30s
      timeout: 10s
      retries: 3


  sonarr:
    profiles: ["torrent", "all"]
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/brescou/sonarr/config:/config
      - /media/brescou/Plex/data/tv:/tv
      - /media/brescou/Plex/data/torrents:/downloads
    restart: no
    depends_on:
      - nordvpn
    network_mode: service:nordvpn
    deploy:
      resources:
        limits:
          memory: 2G

  radarr:
    profiles: ["torrent", "all"]
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/brescou/radarr/config:/config
      - /media/brescou/Plex/data/movies:/movies
      - /media/brescou/Plex/data/torrents:/downloads
    restart: no
    depends_on:
      - nordvpn
    network_mode: service:nordvpn

  prowlarr:
    profiles: ["torrent", "all"]
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/brescou/prowlarr/config:/config
    restart: no
    depends_on:
      - nordvpn
    network_mode: service:nordvpn

